palette:
  top: '#F39433'
  bottom: '#F39433'
  bg: '#ffffff'
  sidebar: '#f1f4f0'
  sidebarborders: '#ededed'
  footer: '#1f1d1c'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#e10075'
logo: 'public://color/bartik-fac10f2c/logo.svg'
stylesheets:
  - 'public://color/bartik-fac10f2c/colors.css'
files:
  - 'public://color/bartik-fac10f2c/logo.svg'
  - 'public://color/bartik-fac10f2c/colors.css'
